### ISSUE TITLE
Accessibility audit

### ISSUE THREAD

**Issue by lucymk** [fac-12/poptart-pickup#40]
You could add alt text to the image, labels to the form and a language to the html to get 100% on the accessibility audit 💯  :1st_place_medal:

**Comment by dangerdak** [comment]
You could add 
- [x] alt text to the image, 
- [x] labels to the form and 
- [x] a language to the html

to get 100% on the accessibility audit

^^^ @lucymk here's a fun way to split up issues that are comprised of multiple tasks - you can tick them off as you go and when looking at your issues list page it will say eg '3/4 completed'

**Comment by njseeto** [comment]
all done :)
